### ISSUE TITLE
Searching for "test" on the test system results in 500 Internal Server Error

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSearch#1]
Nullpointer exception in backend:
03/29 09:08:01.664 ip=138.232.125.205 user=philip gui=1.1.2 DEBUG | [e.t.s.u.SearchUtils, ajp-bio-8010-exec-1654] collIdObjects = null
03/29 09:08:01.665 ip=138.232.125.205 user=philip gui=1.1.2 ERROR | [e.t.s.r.Search, ajp-bio-8010-exec-1654] Could not search in Solr!
java.lang.NullPointerException: null
	at eu.transkribus.solrSearch.util.SearchUtils.generatePageHits(SearchUtils.java:106) ~[TranskribusSearch-0.0.1.jar:na]
	at eu.transkribus.solrSearch.util.SearchUtils.generateSearchResult(SearchUtils.java:50) ~[TranskribusSearch-0.0.1.jar:na]
	at eu.transkribus.solrSearch.TrpSearcher.searchFullText(TrpSearcher.java:85) ~[TranskribusSearch-0.0.1.jar:na]
	at eu.transkribus.persistence.logic.SolrManager.searchFulltext(SolrManager.java:150) ~[TranskribusPersistence-1.0.jar:na]
	at eu.transkribus.server.rest.Search.searchFulltext(Search.java:83) ~[Search.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]

**Comment by kahlep** [comment]
Orphaned documents were indexed and caused this. Fixed in searchUtils and indexer
